Homework #1 (two parts)
epam-js-dec-2018/html-css-1 pull request #2
Opened 2018-12-08 10:05 UTC by freeyoungstrong

I chose Cubes.psd and tried to develop (or maybe more correctly "convert" ) PSD to HTML and CSS.

2018-12-17 07:18 UTC, softcat23 commented on Ruslan Gaiazov/style.css
> +
Можно задать элементам `img` и `aside` классы: не придется дублировать код, уменьшится каскадность, т.к. избыточная каскадность может замедлять работу браузера.
Так же, лучше всегда использовать одно собирательное свойство `padding`(аналогично для `margin`, `border `и т.д.)

2018-12-17 07:18 UTC, softcat23 commented on Ruslan Gaiazov/style.css
> +}
Не очень хорошо использовать `:nth-child()`:
1. Очень сильная привязка css к разметке (если придется добавить еще одну колонку в виджет, то все сломается)
2. Магические числа (стороннему разработчику может быть не сразу понятно, откуда берутся числа)

2018-12-17 07:18 UTC, softcat23 commented on Ruslan Gaiazov/index.html
> +		<div class="weather-big-section" id="section-one">
Не совсем понятно зачем использовать `class`и `id`, нам не нужна такая сильная специфичность, можно было бы написать: `class="section-one weather-big-section"`

2018-12-17 07:20 UTC, softcat23 requested changes
Все поломалось в IE11 :(
![image](https://user-images.githubusercontent.com/45556539/50072184-54999280-01e5-11e9-8f5b-5e35ec348024.png)

2018-12-18 09:29 UTC, freeyoungstrong commented on Ruslan Gaiazov/index.html
> +		<div class="weather-big-section" id="section-one">
Спасибо за комментарии. Постарался исправить замечания. Посмотрите, пожалуйста, когда будет время.

2018-12-18 09:35 UTC, freeyoungstrong commented on Ruslan Gaiazov/style.css
> +
Проблема в том, что картинки погоды имеют разные ширину и длину (кроме первых трех картинок - именно поэтому я их объединил в один класс и немного уменьшил количество строк кода), поэтому разные отступы. Например, для маленьких картинок погоды у меня один класс, потому что их размеры не сильно отличаются друг от друга.

2018-12-18 09:58 UTC, softcat23 commented on Ruslan Gaiazov/style.css
> +
Хорошо, я просто к тому, что у элемента, к примеру `<aside class="cities">chicago / 23&deg;</aside>` уже есть класс, и стили к нему я бы писал как-нибудь так:
```
.cities {
...
}
```
Вместо хитрых селекторов `.first-row aside ` можно же каждому городу(тексту, картинке), при необходимости, свой класс написать. 
Потому что если в HTML нужно будет заменить `aside` на что-нибудь другое, помимо разметки тебе придется переписывать стили. Нет ничего плохого чтобы использовать селекторы `.section-five > img`, но иногда можно усложнить себе жизнь и прибавить работы.
И на счет заменить `aside`, он тут немного не в [тему](https://developer.mozilla.org/ru/docs/Web/HTML/Element/aside) :) лучше взять какой-нибудь `<p>`

2018-12-18 10:24 UTC, freeyoungstrong commented on Ruslan Gaiazov/style.css
> +
понял) знаю, что aside не в тему, но чтоб поменять его на другой тег, нужно как раз переписывать стили, потому что все падает, если просто поменять :D в общем понял, что нужно изменить, спасибо.

2018-12-19 12:56 UTC, freeyoungstrong commented on Ruslan Gaiazov/style.css
> +
Дубль номер 3. 
1) заменил `aside` на `p`.
2) убрал хитрые селекторы. теперь в css только названия классов (и `main` с `img`, который не привязан к отдельному классу).
Жду вашего мнения.

2018-12-23 11:20 UTC, fat23cat commented
Код выглядит неплохо, молодец.
Только в IE и Chrome немного различаются шрифты и немного пляшут градусы с иконками погоды:
![image](https://user-images.githubusercontent.com/30126907/50383077-cda15a00-06bd-11e9-9c6a-5b0c69116fad.png)

2018-12-23 11:22 UTC, softcat23 commented
Код выглядит неплохо, молодец.
Только в IE и Chrome немного различаются шрифты и немного пляшут градусы с иконками погоды:
![image](https://user-images.githubusercontent.com/45556539/50383100-1bb65d80-06be-11e9-96dc-07c104523c42.png)

2018-12-27 18:19 UTC, freeyoungstrong commented
@softcat23, поменял формат шрифта. woff легче, чем ttf, поэтому IE11 теперь загружает его

2019-01-27 12:14 UTC, merged